// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/alkabir-challenge/IndigoNight.tsx": () => import("../components/mockups/alkabir-challenge/IndigoNight.tsx"),
  "./components/mockups/alkabir-challenge/PlumRose.tsx": () => import("../components/mockups/alkabir-challenge/PlumRose.tsx"),
  "./components/mockups/alkabir-challenge/QuizFlow.tsx": () => import("../components/mockups/alkabir-challenge/QuizFlow.tsx"),
  "./components/mockups/alkabir-challenge/WarmSand.tsx": () => import("../components/mockups/alkabir-challenge/WarmSand.tsx")
};
